### ISSUE TITLE
Prepare public status on Github

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-restapi#67]
### Assessment
- A complete rebase is required because real usernames and passwords were hardcoded at some point.

### TODO
- [x] Scan for security leaks
    - [x] passed: `truffleHog --regex --entropy=False https://github.com/satzbeleg/evidence-restapi.git` 
    - [x] passed, only old toy credentials: `gittyleaks -link https://github.com/satzbeleg/evidence-restapi`
- [x] Fix unit test bugs 
- [ ] add all missing docstr
- [ ] Delete unnecessary comments and code
- [x] Translate comments/readme to EN
- [ ] Transfer the whole repo to a backup location (incl. issues)
- [ ] Create a new repo with a clean code version as initial upload
