### ISSUE TITLE
Remove Auth Service from EV project

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-restapi#77]
## Related Issue
- [ ] https://github.com/satzbeleg/evidence-database/issues/66

## TODO
- [ ] Create a new repo with FastAPI and PSQL (https://github.com/satzbeleg/evidence-database/issues/66)
- [ ] Implement Auth API call from application API
- [ ] Ensure that `Depends(auth_email.get_current_user)` works in `./app/main.py`
