### ISSUE TITLE
Click on E-Mail verfification link returns obscure REST API response that might confuse users

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-restapi#85]
## TODO
- [ ] Display a pretty HTML page: 
    - [ ] Text centered on the screen
    - [ ] nice Bulma button to goto the app (other port)
